-- Demo data for local development.
--
-- Assumes a freshly migrated, otherwise-empty database (all of db/migrations/
-- V1-V8 applied). Explicit IDs are used since users/categories/tasks are
-- GENERATED BY DEFAULT AS IDENTITY, which still allows an explicit value on
-- insert -- this keeps the seed deterministic and the FK references below
-- simple to read.
--
-- Demo login: demo@example.com / DemoPass123
-- (password_hash below is a real bcrypt hash of that password, cost factor 10,
-- matching SALT_ROUNDS in backend/src/services/auth.service.js)

INSERT INTO users (user_id, username, email, password_hash)
VALUES (1, 'demo', 'demo@example.com', '$2b$10$T2UIO7J.Z.Cgi7xiWjzPhewOLuroml9KSGyQEF14KnHkNRW/HTuUq');

INSERT INTO categories (category_id, user_id, name) VALUES (1, 1, 'Work');
INSERT INTO categories (category_id, user_id, name) VALUES (2, 1, 'Personal');
INSERT INTO categories (category_id, user_id, name) VALUES (3, 1, 'Urgent');

-- Due 2026-06-01, before "today" in this project's working context -- renders
-- as overdue out of the box, useful for exercising the dashboard/list without
-- extra setup.
INSERT INTO tasks (task_id, user_id, title, description, priority, status, due_date)
VALUES (1, 1, 'Renew car registration', NULL, 'Medium', 'Pending', DATE '2026-06-01');

INSERT INTO tasks (task_id, user_id, title, description, priority, status, due_date)
VALUES (2, 1, 'Finish quarterly report', 'Pull numbers from the finance dashboard first.', 'High', 'Pending', DATE '2026-08-15');

INSERT INTO tasks (task_id, user_id, title, description, priority, status, due_date)
VALUES (3, 1, 'Book dentist appointment', NULL, 'Low', 'Completed', DATE '2026-07-01');

INSERT INTO tasks (task_id, user_id, title, description, priority, status, due_date)
VALUES (4, 1, 'Prepare team offsite agenda', 'Include an icebreaker and the budget review.', 'High', 'In Progress', DATE '2026-08-01');

-- Task 4 demonstrates a task with multiple categories.
INSERT INTO task_categories (task_id, category_id) VALUES (1, 2);
INSERT INTO task_categories (task_id, category_id) VALUES (2, 1);
INSERT INTO task_categories (task_id, category_id) VALUES (4, 1);
INSERT INTO task_categories (task_id, category_id) VALUES (4, 3);

COMMIT;
