CREATE TABLE users (
    user_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR2(100) NOT NULL,
    email           VARCHAR2(255) NOT NULL,
    password_hash   VARCHAR2(255) NOT NULL,
    created_date    TIMESTAMP NOT NULL DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    CONSTRAINT uq_users_email UNIQUE (email)
);
