CREATE TABLE tasks (
    task_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER NOT NULL,
    category_id     NUMBER,
    title           VARCHAR2(200) NOT NULL,
    description     VARCHAR2(4000),
    priority        VARCHAR2(10) NOT NULL,
    status          VARCHAR2(20) NOT NULL,
    due_date        DATE NOT NULL,
    created_date    TIMESTAMP NOT NULL DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    CONSTRAINT fk_tasks_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT fk_tasks_category FOREIGN KEY (category_id)
        REFERENCES categories(category_id) ON DELETE SET NULL,
    CONSTRAINT ck_tasks_priority CHECK (priority IN ('High','Medium','Low')),
    CONSTRAINT ck_tasks_status CHECK (status IN ('Pending','In Progress','Completed','Cancelled'))
);
